export const UNIQUE_CLOTHES_CATEGORIES = [
  "shirt",
  "pants",
  "jacket",
  "dress",
  "skirt",
  "sweater",
  "shorts",
  "blouse",
  "coat",
  "hoodie",
  "suit",
  "jeans",
];

export const RANDOM_CLOTHES_CATEGORIES = [
  ["hoodie", "hoodie", "coat", "sweater", "coat"],
  [
    "suit",
    "shirt",
    "sweater",
    "jacket",
    "hoodie",
    "pants",
    "skirt",
    "skirt",
    "skirt",
    "jeans",
    "shirt",
    "blouse",
    "jacket",
    "dress",
    "sweater",
    "dress",
    "pants",
    "coat",
  ],
  ["blouse", "hoodie"],
  ["jacket", "skirt", "jeans", "hoodie", "jacket"],
  ["pants", "pants", "jeans", "shirt", "hoodie", "shorts", "suit", "jeans", "coat", "sweater", "blouse"],
  ["sweater", "blouse", "dress", "skirt", "shorts"],
  [
    "sweater",
    "sweater",
    "sweater",
    "jeans",
    "suit",
    "skirt",
    "skirt",
    "shorts",
    "blouse",
    "skirt",
    "jacket",
    "pants",
    "hoodie",
    "hoodie",
    "jacket",
  ],
  ["suit", "hoodie", "shorts"],
  ["jeans", "jeans", "shirt", "hoodie", "coat", "suit", "hoodie", "coat"],
  ["sweater", "jeans", "sweater", "coat"],
  [
    "pants",
    "blouse",
    "hoodie",
    "skirt",
    "jeans",
    "suit",
    "shirt",
    "blouse",
    "shirt",
    "blouse",
    "skirt",
    "shorts",
    "dress",
    "sweater",
    "coat",
  ],
  ["suit", "pants", "sweater", "coat", "coat", "skirt", "blouse", "shirt", "sweater"],
  [
    "blouse",
    "hoodie",
    "coat",
    "coat",
    "jeans",
    "dress",
    "shorts",
    "jeans",
    "blouse",
    "jeans",
    "dress",
    "jeans",
    "shorts",
    "hoodie",
    "blouse",
  ],
  ["pants", "shorts", "shorts", "skirt", "blouse", "suit", "shirt", "shirt", "shirt", "coat", "shirt"],
  ["shorts", "skirt", "jacket", "pants", "shorts", "jacket"],
  ["shorts", "blouse", "jeans", "jeans", "blouse", "pants", "dress", "jeans"],
  ["shorts", "suit", "skirt"],
  ["shirt", "sweater", "dress", "jacket", "blouse", "suit", "pants", "dress", "pants", "shirt"],
  ["sweater", "dress", "suit"],
  [
    "pants",
    "jeans",
    "jeans",
    "suit",
    "blouse",
    "jeans",
    "skirt",
    "dress",
    "sweater",
    "shirt",
    "hoodie",
    "dress",
    "hoodie",
    "skirt",
    "dress",
    "suit",
    "blouse",
    "coat",
  ],
  [
    "dress",
    "shirt",
    "suit",
    "shirt",
    "shirt",
    "suit",
    "dress",
    "shorts",
    "coat",
    "skirt",
    "shorts",
    "dress",
    "jeans",
    "shorts",
    "shorts",
    "pants",
    "suit",
    "jacket",
    "jacket",
  ],
  ["coat", "jeans"],
  ["skirt", "blouse", "jacket", "coat", "coat", "hoodie", "shirt", "blouse", "blouse", "coat", "skirt"],
  ["blouse", "jeans", "dress"],
  ["blouse", "blouse", "sweater", "hoodie", "blouse", "coat"],
  [
    "sweater",
    "coat",
    "shorts",
    "sweater",
    "suit",
    "shirt",
    "suit",
    "shorts",
    "coat",
    "blouse",
    "skirt",
    "suit",
    "shirt",
    "shirt",
    "sweater",
    "coat",
    "sweater",
  ],
  [
    "skirt",
    "shorts",
    "dress",
    "shirt",
    "coat",
    "pants",
    "shorts",
    "skirt",
    "dress",
    "jeans",
    "coat",
    "coat",
    "coat",
    "dress",
    "dress",
    "shirt",
    "skirt",
    "skirt",
  ],
  ["jeans", "jacket"],
  [
    "skirt",
    "hoodie",
    "jacket",
    "shirt",
    "pants",
    "coat",
    "sweater",
    "jacket",
    "blouse",
    "hoodie",
    "jeans",
    "pants",
    "jeans",
    "hoodie",
    "skirt",
    "coat",
    "hoodie",
    "pants",
    "coat",
  ],
  [
    "suit",
    "jeans",
    "hoodie",
    "jacket",
    "jeans",
    "skirt",
    "coat",
    "dress",
    "shirt",
    "pants",
    "skirt",
    "shirt",
    "pants",
    "hoodie",
  ],
  ["blouse", "dress", "shorts", "blouse", "blouse", "sweater", "pants", "skirt"],
  [
    "suit",
    "sweater",
    "pants",
    "sweater",
    "blouse",
    "dress",
    "shirt",
    "coat",
    "skirt",
    "hoodie",
    "suit",
    "blouse",
    "hoodie",
  ],
  ["sweater", "suit", "skirt", "shirt"],
  ["jacket", "jacket", "shorts", "jacket", "blouse", "pants", "jeans", "shorts", "coat", "suit"],
  ["suit", "jacket", "suit", "skirt", "shorts", "jacket"],
  [
    "suit",
    "pants",
    "shirt",
    "hoodie",
    "skirt",
    "pants",
    "hoodie",
    "jacket",
    "dress",
    "skirt",
    "hoodie",
    "skirt",
    "dress",
    "pants",
    "blouse",
    "sweater",
    "coat",
    "blouse",
    "suit",
  ],
  [
    "suit",
    "shorts",
    "hoodie",
    "suit",
    "shirt",
    "hoodie",
    "suit",
    "shirt",
    "pants",
    "hoodie",
    "shorts",
    "jeans",
    "sweater",
    "coat",
    "skirt",
    "blouse",
    "coat",
    "blouse",
  ],
  ["coat", "skirt", "blouse", "coat"],
  ["jeans", "coat", "shorts", "hoodie", "coat", "coat", "coat", "sweater", "blouse"],
  ["blouse", "shorts"],
  [
    "shorts",
    "dress",
    "suit",
    "pants",
    "hoodie",
    "pants",
    "shorts",
    "sweater",
    "jeans",
    "suit",
    "shirt",
    "jacket",
    "suit",
    "sweater",
    "jacket",
    "shirt",
  ],
  ["sweater", "hoodie", "shorts", "jacket", "jacket", "pants", "jacket", "shorts", "shorts"],
  [
    "dress",
    "jacket",
    "jacket",
    "suit",
    "jacket",
    "skirt",
    "jacket",
    "suit",
    "shorts",
    "sweater",
    "jacket",
    "jacket",
    "shorts",
    "dress",
    "skirt",
    "pants",
    "dress",
    "sweater",
    "dress",
  ],
  ["coat", "coat", "coat", "sweater", "coat", "skirt", "dress", "suit"],
  ["blouse", "pants", "coat", "jeans", "dress", "shorts", "hoodie", "shorts", "jeans", "blouse", "shirt", "coat"],
  ["suit", "dress", "suit", "dress", "shirt", "suit", "coat", "blouse", "shorts", "hoodie", "shirt"],
  ["shorts", "hoodie", "coat", "blouse", "blouse", "shirt", "sweater", "coat"],
  [
    "hoodie",
    "pants",
    "jacket",
    "shorts",
    "pants",
    "shorts",
    "blouse",
    "dress",
    "shorts",
    "suit",
    "skirt",
    "suit",
    "shorts",
    "hoodie",
    "suit",
  ],
  ["dress", "shorts", "shorts", "dress", "suit", "jacket", "jacket", "shorts", "skirt", "blouse", "jacket"],
  [
    "shorts",
    "skirt",
    "hoodie",
    "coat",
    "shirt",
    "suit",
    "suit",
    "blouse",
    "pants",
    "jeans",
    "shirt",
    "pants",
    "shirt",
    "dress",
  ],
];

export const CARBON_FOOTPRINTS: Record<string, number> = {
  shirt: 10,
  pants: 15,
  jacket: 20,
  dress: 25,
  skirt: 18,
  sweater: 22,
  shorts: 12,
  blouse: 14,
  coat: 30,
  hoodie: 28,
  suit: 35,
  jeans: 16,
};

export const OFFERS = [
  {
    brandName: "Starbucks",
    brandLogo: "https://1000logos.net/wp-content/uploads/2023/04/Starbucks-logo.png",
    offerMessage: "Flat 30% Off",
    validTill: "2025-09-08",
    pointsRequired: 81,
  },
  {
    brandName: "Nike",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/03/Nike-Logo.png",
    offerMessage: "Flash Deal Today Only",
    validTill: "2025-07-29",
    pointsRequired: 94,
  },
  {
    brandName: "McDonald's",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/03/McDonalds-logo.png",
    offerMessage: "Early Access Sale",
    validTill: "2025-09-05",
    pointsRequired: 13,
  },
  {
    brandName: "Gucci",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/01/Gucci-Logo.png",
    offerMessage: "Buy 1 Get 1 Free!",
    validTill: "2025-08-12",
    pointsRequired: 82,
  },
  {
    brandName: "Domino's",
    brandLogo: "https://1000logos.net/wp-content/uploads/2023/04/Dominos-logo.png",
    offerMessage: "Get Free Goodies!",
    validTill: "2025-07-24",
    pointsRequired: 80,
  },
  {
    brandName: "Apple",
    brandLogo: "https://1000logos.net/wp-content/uploads/2016/10/Apple-Logo.png",
    offerMessage: "Flat 30% Off",
    validTill: "2025-07-29",
    pointsRequired: 19,
  },
  {
    brandName: "Amazon",
    brandLogo: "https://1000logos.net/wp-content/uploads/2016/10/Amazon-Logo.png",
    offerMessage: "Flat 30% Off",
    validTill: "2025-07-21",
    pointsRequired: 99,
  },
  {
    brandName: "Adidas",
    brandLogo: "https://1000logos.net/wp-content/uploads/2016/10/Adidas-Logo.png",
    offerMessage: "Free Shipping on Orders Above ₹999",
    validTill: "2025-08-25",
    pointsRequired: 59,
  },
  {
    brandName: "H&M",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/02/HM-Logo.png",
    offerMessage: "Extra 10% Cashback",
    validTill: "2025-07-15",
    pointsRequired: 71,
  },
  {
    brandName: "Samsung",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/06/Samsung-Logo.png",
    offerMessage: "Extra 10% Cashback",
    validTill: "2025-09-03",
    pointsRequired: 41,
  },
  {
    brandName: "Pepsi",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/05/Pepsi-logo.png",
    offerMessage: "Free Shipping on Orders Above ₹999",
    validTill: "2025-08-15",
    pointsRequired: 41,
  },
  {
    brandName: "Coca-Cola",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/05/Coca-Cola-logo.png",
    offerMessage: "Extra 10% Cashback",
    validTill: "2025-07-21",
    pointsRequired: 100,
  },
  {
    brandName: "KFC",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/03/Kfc_logo.png",
    offerMessage: "Flat ₹500 Off",
    validTill: "2025-08-16",
    pointsRequired: 15,
  },
  {
    brandName: "Subway",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/06/Subway-logo.png",
    offerMessage: "Flat 30% Off",
    validTill: "2025-09-29",
    pointsRequired: 41,
  },
  {
    brandName: "Puma",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/04/Puma-logo.png",
    offerMessage: "Early Access Sale",
    validTill: "2025-07-22",
    pointsRequired: 75,
  },
  {
    brandName: "Levi's",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/03/Levis-Logo.png",
    offerMessage: "Free Shipping on Orders Above ₹999",
    validTill: "2025-07-29",
    pointsRequired: 36,
  },
  {
    brandName: "Reebok",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/05/Reebok-logo.png",
    offerMessage: "Early Access Sale",
    validTill: "2025-09-02",
    pointsRequired: 43,
  },
  {
    brandName: "Burger King",
    brandLogo: "https://1000logos.net/wp-content/uploads/2016/10/Burger-King_Logo.png",
    offerMessage: "Exclusive Member Discount",
    validTill: "2025-09-28",
    pointsRequired: 79,
  },
  {
    brandName: "Tesla",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/04/Tesla-logo.png",
    offerMessage: "Buy 1 Get 1 Free!",
    validTill: "2025-08-20",
    pointsRequired: 99,
  },
  {
    brandName: "Sony",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/05/Sony-logo.png",
    offerMessage: "Free Shipping on Orders Above ₹999",
    validTill: "2025-09-12",
    pointsRequired: 66,
  },
  {
    brandName: "Google",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/05/Google-logo.png",
    offerMessage: "Exclusive Member Discount",
    validTill: "2025-08-08",
    pointsRequired: 20,
  },
  {
    brandName: "Microsoft",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/04/Microsoft-Logo.png",
    offerMessage: "Extra 10% Cashback",
    validTill: "2025-08-12",
    pointsRequired: 76,
  },
  {
    brandName: "L'Oreal",
    brandLogo: "https://1000logos.net/wp-content/uploads/2022/04/LOreal-logo.png",
    offerMessage: "Limited Time Deal",
    validTill: "2025-07-27",
    pointsRequired: 48,
  },
  {
    brandName: "LG",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/03/LG-Logo.png",
    offerMessage: "Flat 30% Off",
    validTill: "2025-10-03",
    pointsRequired: 26,
  },
  {
    brandName: "Panasonic",
    brandLogo: "https://1000logos.net/wp-content/uploads/2022/12/Panasonic-logo.png",
    offerMessage: "Get Free Goodies!",
    validTill: "2025-08-28",
    pointsRequired: 86,
  },
  {
    brandName: "Asus",
    brandLogo: "https://1000logos.net/wp-content/uploads/2016/10/Asus-Logo.png",
    offerMessage: "Flat 30% Off",
    validTill: "2025-09-30",
    pointsRequired: 82,
  },
  {
    brandName: "Dell",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/07/Dell-Logo.png",
    offerMessage: "Flat 30% Off",
    validTill: "2025-08-15",
    pointsRequired: 81,
  },
  {
    brandName: "HP",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/02/HP-Log%D0%BE.png",
    offerMessage: "Early Access Sale",
    validTill: "2025-09-06",
    pointsRequired: 47,
  },
  {
    brandName: "Uber",
    brandLogo:
      "https://1000logos.net/wp-content/uploads/2025/05/The-Story-Behind-Ubers-Modern-and-Sleek-Logo-Design.png",
    offerMessage: "Free Shipping on Orders Above ₹999",
    validTill: "2025-08-24",
    pointsRequired: 40,
  },
  {
    brandName: "Lyft",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/11/Lyft-Logo.png",
    offerMessage: "Extra 10% Cashback",
    validTill: "2025-08-31",
    pointsRequired: 84,
  },
  {
    brandName: "Snapchat",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/08/Snapchat-logo.png",
    offerMessage: "Flash Deal Today Only",
    validTill: "2025-09-10",
    pointsRequired: 12,
  },
  {
    brandName: "Instagram",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/02/Instagram-Logo.png",
    offerMessage: "Extra 10% Cashback",
    validTill: "2025-08-06",
    pointsRequired: 41,
  },
  {
    brandName: "YouTube Music",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/12/YouTube-Music-Logo.png",
    offerMessage: "Buy 1 Get 1 Free!",
    validTill: "2025-07-16",
    pointsRequired: 15,
  },
  {
    brandName: "Netflix",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/05/Netflix-Logo.png",
    offerMessage: "Get Free Goodies!",
    validTill: "2025-09-15",
    pointsRequired: 19,
  },
  {
    brandName: "Spotify",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/11/Spotify-Logo.png",
    offerMessage: "Limited Time Deal",
    validTill: "2025-09-27",
    pointsRequired: 62,
  },
  {
    brandName: "Tinder",
    brandLogo: "https://1000logos.net/wp-content/uploads/2018/07/Tinder-logo.png",
    offerMessage: "Free membership for a month",
    validTill: "2025-09-25",
    pointsRequired: 75,
  },
  {
    brandName: "Airbnb",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/08/Airbnb-Logo.png",
    offerMessage: "Get Free Goodies!",
    validTill: "2025-09-07",
    pointsRequired: 67,
  },
  {
    brandName: "Swiggy",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/05/Swiggy-logo.png",
    offerMessage: "Flash Deal Today Only",
    validTill: "2025-08-15",
    pointsRequired: 36,
  },
  {
    brandName: "Zomato",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/06/Zomato-logo.png",
    offerMessage: "Flash Deal Today Only",
    validTill: "2025-09-18",
    pointsRequired: 17,
  },
  {
    brandName: "Nokia",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/03/Nokia-Logo.png",
    offerMessage: "Flat 30% Off on mobile accessories",
    validTill: "2025-07-17",
    pointsRequired: 58,
  },
  {
    brandName: "DoorDash",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/06/DoorDash-logo.png",
    offerMessage: "Exclusive Discount on orders",
    validTill: "2025-09-27",
    pointsRequired: 64,
  },
  {
    brandName: "Ajio",
    brandLogo: "https://1000logos.net/wp-content/uploads/2020/07/Ajio-Logo.png",
    offerMessage: "Early Access Sale",
    validTill: "2025-09-14",
    pointsRequired: 21,
  },
  {
    brandName: "Myntra",
    brandLogo: "https://1000logos.net/wp-content/uploads/2022/08/Myntra-Logo.png",
    offerMessage: "Buy 1 Get 1 Free!",
    validTill: "2025-09-22",
    pointsRequired: 79,
  },
  {
    brandName: "Flipkart",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/02/Flipkart-logo.png",
    offerMessage: "Exclusive Member Discount",
    validTill: "2025-07-28",
    pointsRequired: 66,
  },
  {
    brandName: "Red Bull",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/05/Red-Bull-logo.png",
    offerMessage: "Free Shipping on Orders Above ₹999",
    validTill: "2025-07-27",
    pointsRequired: 49,
  },
  {
    brandName: "Unilever",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/06/Unilever-Logo.png",
    offerMessage: "Buy 1 Get 1 Free!",
    validTill: "2025-08-12",
    pointsRequired: 28,
  },
  {
    brandName: "Nestle",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/03/Nestle-Logo.png",
    offerMessage: "Flat ₹500 Off",
    validTill: "2025-08-29",
    pointsRequired: 67,
  },
  {
    brandName: "Visa",
    brandLogo: "https://1000logos.net/wp-content/uploads/2021/11/VISA-logo.png",
    offerMessage: "Get Free Goodies!",
    validTill: "2025-08-12",
    pointsRequired: 38,
  },
  {
    brandName: "MuleSoft",
    brandLogo: "https://1000logos.net/wp-content/uploads/2024/08/MuleSoft-Logo.png",
    offerMessage: "Early Access Sale",
    validTill: "2025-09-23",
    pointsRequired: 22,
  },
  {
    brandName: "IKEA",
    brandLogo: "https://1000logos.net/wp-content/uploads/2017/02/IKEA-Logo.png",
    offerMessage: "Flat ₹500 Off",
    validTill: "2025-09-18",
    pointsRequired: 13,
  },
];
